go:
    version: 1.8
    cgo: false
repository:
    path: github.com/chronojam/dexy
build:
    flags: -a -tags netgo
    binaries:
        - name: dexy
          path: ./cmd
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        - windows/amd64
